[package]
name = "lv2-host"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2-sys = "2.0.0"
libloading = "0.7.0"
