//! Since this crate uses `bindgen` to create the C API bindings, you need to have clang installed on your machine.
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
#[allow(clippy::all)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::{
    LV2_MIDI__ActiveSense, LV2_MIDI__Aftertouch, LV2_MIDI__Bender, LV2_MIDI__ChannelPressure,
    LV2_MIDI__Chunk, LV2_MIDI__Clock, LV2_MIDI__Continue, LV2_MIDI__Controller,
    LV2_MIDI__MidiEvent, LV2_MIDI__NoteOff, LV2_MIDI__NoteOn, LV2_MIDI__ProgramChange,
    LV2_MIDI__QuarterFrame, LV2_MIDI__Reset, LV2_MIDI__SongPosition, LV2_MIDI__SongSelect,
    LV2_MIDI__Start, LV2_MIDI__Stop, LV2_MIDI__SystemCommon, LV2_MIDI__SystemExclusive,
    LV2_MIDI__SystemMessage, LV2_MIDI__SystemRealtime, LV2_MIDI__Tick, LV2_MIDI__TuneRequest,
    LV2_MIDI__VoiceMessage, LV2_MIDI__benderValue, LV2_MIDI__binding, LV2_MIDI__byteNumber,
    LV2_MIDI__channel, LV2_MIDI__chunk, LV2_MIDI__controllerNumber, LV2_MIDI__controllerValue,
    LV2_MIDI__noteNumber, LV2_MIDI__pressure, LV2_MIDI__programNumber, LV2_MIDI__property,
    LV2_MIDI__songNumber, LV2_MIDI__songPosition, LV2_MIDI__status, LV2_MIDI__statusMask,
    LV2_MIDI__velocity, LV2_Midi_Controller, LV2_Midi_Controller_LV2_MIDI_CTL_ALL_NOTES_OFF,
    LV2_Midi_Controller_LV2_MIDI_CTL_ALL_SOUNDS_OFF,
    LV2_Midi_Controller_LV2_MIDI_CTL_DATA_DECREMENT,
    LV2_Midi_Controller_LV2_MIDI_CTL_DATA_INCREMENT,
    LV2_Midi_Controller_LV2_MIDI_CTL_E1_REVERB_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E2_TREMOLO_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E3_CHORUS_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E4_DETUNE_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E5_PHASER_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE5,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE6,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE7,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE8, LV2_Midi_Controller_LV2_MIDI_CTL_HOLD2,
    LV2_Midi_Controller_LV2_MIDI_CTL_LEGATO_FOOTSWITCH,
    LV2_Midi_Controller_LV2_MIDI_CTL_LOCAL_CONTROL_SWITCH,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_BALANCE, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_BANK,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_BREATH, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_DATA_ENTRY,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_EFFECT1, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_EFFECT2,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_EXPRESSION, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_FOOT,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE1,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE2,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE3,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE4,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_MAIN_VOLUME,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_MODWHEEL, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_PAN,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_PORTAMENTO_TIME, LV2_Midi_Controller_LV2_MIDI_CTL_MONO1,
    LV2_Midi_Controller_LV2_MIDI_CTL_MONO2, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_BALANCE,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_BANK, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_BREATH,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_DATA_ENTRY, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_EFFECT1,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_EFFECT2, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_EXPRESSION,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_FOOT,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE1,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE2,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE3,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE4,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_MAIN_VOLUME,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_MODWHEEL, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_PAN,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_PORTAMENTO_TIME,
    LV2_Midi_Controller_LV2_MIDI_CTL_NRPN_LSB, LV2_Midi_Controller_LV2_MIDI_CTL_NRPN_MSB,
    LV2_Midi_Controller_LV2_MIDI_CTL_OMNI_OFF, LV2_Midi_Controller_LV2_MIDI_CTL_OMNI_ON,
    LV2_Midi_Controller_LV2_MIDI_CTL_PORTAMENTO,
    LV2_Midi_Controller_LV2_MIDI_CTL_PORTAMENTO_CONTROL,
    LV2_Midi_Controller_LV2_MIDI_CTL_RESET_CONTROLLERS, LV2_Midi_Controller_LV2_MIDI_CTL_RPN_LSB,
    LV2_Midi_Controller_LV2_MIDI_CTL_RPN_MSB, LV2_Midi_Controller_LV2_MIDI_CTL_SC10,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC1_SOUND_VARIATION,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC2_TIMBRE, LV2_Midi_Controller_LV2_MIDI_CTL_SC3_RELEASE_TIME,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC4_ATTACK_TIME,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC5_BRIGHTNESS, LV2_Midi_Controller_LV2_MIDI_CTL_SC6,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC7, LV2_Midi_Controller_LV2_MIDI_CTL_SC8,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC9, LV2_Midi_Controller_LV2_MIDI_CTL_SOFT_PEDAL,
    LV2_Midi_Controller_LV2_MIDI_CTL_SOSTENUTO, LV2_Midi_Controller_LV2_MIDI_CTL_SUSTAIN,
    LV2_Midi_Message_Type, LV2_Midi_Message_Type_LV2_MIDI_MSG_ACTIVE_SENSE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_BENDER, LV2_Midi_Message_Type_LV2_MIDI_MSG_CHANNEL_PRESSURE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_CLOCK, LV2_Midi_Message_Type_LV2_MIDI_MSG_CONTINUE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_CONTROLLER, LV2_Midi_Message_Type_LV2_MIDI_MSG_INVALID,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_MTC_QUARTER, LV2_Midi_Message_Type_LV2_MIDI_MSG_NOTE_OFF,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_NOTE_ON, LV2_Midi_Message_Type_LV2_MIDI_MSG_NOTE_PRESSURE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_PGM_CHANGE, LV2_Midi_Message_Type_LV2_MIDI_MSG_RESET,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_SONG_POS, LV2_Midi_Message_Type_LV2_MIDI_MSG_SONG_SELECT,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_START, LV2_Midi_Message_Type_LV2_MIDI_MSG_STOP,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_SYSTEM_EXCLUSIVE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_TUNE_REQUEST, LV2_MIDI_PREFIX, LV2_MIDI_URI,
};
