[package]
name = "sampler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2 = { path = "../..", features = ["lv2-worker"] }
hound = "3.4.0"