//! Since this crate uses `bindgen` to create the C API bindings, you need to have clang installed on your machine.
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
#[allow(clippy::all)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use bindings::{
    LV2UI_Controller, LV2UI_DescriptorFunction, LV2UI_Feature_Handle, LV2UI_Handle, LV2UI_Widget,
    LV2UI_Write_Function, LV2_Atom, LV2_Atom_Bool, LV2_Atom_Double, LV2_Atom_Event, LV2_Atom_Float,
    LV2_Atom_Int, LV2_Atom_Literal, LV2_Atom_Literal_Body, LV2_Atom_Long, LV2_Atom_Object,
    LV2_Atom_Object_Body, LV2_Atom_Property, LV2_Atom_Property_Body, LV2_Atom_Sequence,
    LV2_Atom_Sequence_Body, LV2_Atom_String, LV2_Atom_Tuple, LV2_Atom_URID, LV2_Atom_Vector,
    LV2_Atom_Vector_Body, LV2_Descriptor_Function, LV2_Dyn_Manifest_Handle,
    LV2_Extension_Data_Feature, LV2_Handle, LV2_Lib_Descriptor, LV2_Lib_Descriptor_Function,
    LV2_Lib_Handle, LV2_Log_Handle, LV2_Midi_Controller, LV2_Midi_Message_Type,
    LV2_Options_Context, LV2_Options_Status, LV2_Resize_Port_Feature_Data, LV2_Resize_Port_Resize,
    LV2_Resize_Port_Status, LV2_State_Flags, LV2_State_Free_Path, LV2_State_Free_Path_Handle,
    LV2_State_Handle, LV2_State_Make_Path, LV2_State_Make_Path_Handle, LV2_State_Map_Path,
    LV2_State_Map_Path_Handle, LV2_State_Retrieve_Function, LV2_State_Status,
    LV2_State_Store_Function, LV2_URID_Map_Handle, LV2_URID_Unmap_Handle,
    LV2_Worker_Respond_Function, LV2_Worker_Respond_Handle, LV2_Worker_Schedule_Handle,
    LV2_Worker_Status, LV2_URID,
};

pub use bindings::{
    LV2_ATOM__Atom, LV2_ATOM__AtomPort, LV2_ATOM__Blank, LV2_ATOM__Bool, LV2_ATOM__Chunk,
    LV2_ATOM__Double, LV2_ATOM__Event, LV2_ATOM__Float, LV2_ATOM__Int, LV2_ATOM__Literal,
    LV2_ATOM__Long, LV2_ATOM__Number, LV2_ATOM__Object, LV2_ATOM__Path, LV2_ATOM__Property,
    LV2_ATOM__Resource, LV2_ATOM__Sequence, LV2_ATOM__Sound, LV2_ATOM__String, LV2_ATOM__Tuple,
    LV2_ATOM__Vector, LV2_ATOM__atomTransfer, LV2_ATOM__beatTime, LV2_ATOM__bufferType,
    LV2_ATOM__childType, LV2_ATOM__eventTransfer, LV2_ATOM__frameTime, LV2_ATOM__supports,
    LV2_ATOM__timeUnit, LV2_BUF_SIZE__boundedBlockLength, LV2_BUF_SIZE__fixedBlockLength,
    LV2_BUF_SIZE__maxBlockLength, LV2_BUF_SIZE__minBlockLength, LV2_BUF_SIZE__nominalBlockLength,
    LV2_BUF_SIZE__powerOf2BlockLength, LV2_BUF_SIZE__sequenceSize, LV2_CORE__AllpassPlugin,
    LV2_CORE__AmplifierPlugin, LV2_CORE__AnalyserPlugin, LV2_CORE__AudioPort,
    LV2_CORE__BandpassPlugin, LV2_CORE__CVPort, LV2_CORE__ChorusPlugin, LV2_CORE__CombPlugin,
    LV2_CORE__CompressorPlugin, LV2_CORE__ConstantPlugin, LV2_CORE__ControlPort,
    LV2_CORE__ConverterPlugin, LV2_CORE__DelayPlugin, LV2_CORE__DistortionPlugin,
    LV2_CORE__DynamicsPlugin, LV2_CORE__EQPlugin, LV2_CORE__EnvelopePlugin,
    LV2_CORE__ExpanderPlugin, LV2_CORE__ExtensionData, LV2_CORE__Feature, LV2_CORE__FilterPlugin,
    LV2_CORE__FlangerPlugin, LV2_CORE__FunctionPlugin, LV2_CORE__GatePlugin,
    LV2_CORE__GeneratorPlugin, LV2_CORE__HighpassPlugin, LV2_CORE__InputPort,
    LV2_CORE__InstrumentPlugin, LV2_CORE__LimiterPlugin, LV2_CORE__LowpassPlugin,
    LV2_CORE__MixerPlugin, LV2_CORE__ModulatorPlugin, LV2_CORE__MultiEQPlugin,
    LV2_CORE__OscillatorPlugin, LV2_CORE__OutputPort, LV2_CORE__ParaEQPlugin,
    LV2_CORE__PhaserPlugin, LV2_CORE__PitchPlugin, LV2_CORE__Plugin, LV2_CORE__PluginBase,
    LV2_CORE__Point, LV2_CORE__Port, LV2_CORE__PortProperty, LV2_CORE__Resource,
    LV2_CORE__ReverbPlugin, LV2_CORE__ScalePoint, LV2_CORE__SimulatorPlugin,
    LV2_CORE__SpatialPlugin, LV2_CORE__Specification, LV2_CORE__SpectralPlugin,
    LV2_CORE__UtilityPlugin, LV2_CORE__WaveshaperPlugin, LV2_CORE__appliesTo, LV2_CORE__binary,
    LV2_CORE__connectionOptional, LV2_CORE__control, LV2_CORE__default, LV2_CORE__designation,
    LV2_CORE__documentation, LV2_CORE__enumeration, LV2_CORE__extensionData,
    LV2_CORE__freeWheeling, LV2_CORE__hardRTCapable, LV2_CORE__inPlaceBroken, LV2_CORE__index,
    LV2_CORE__integer, LV2_CORE__isLive, LV2_CORE__latency, LV2_CORE__maximum,
    LV2_CORE__microVersion, LV2_CORE__minimum, LV2_CORE__minorVersion, LV2_CORE__name,
    LV2_CORE__optionalFeature, LV2_CORE__port, LV2_CORE__portProperty, LV2_CORE__project,
    LV2_CORE__prototype, LV2_CORE__reportsLatency, LV2_CORE__requiredFeature, LV2_CORE__sampleRate,
    LV2_CORE__scalePoint, LV2_CORE__symbol, LV2_CORE__toggled, LV2_LOG__Entry, LV2_LOG__Error,
    LV2_LOG__Note, LV2_LOG__Trace, LV2_LOG__Warning, LV2_LOG__log, LV2_MIDI__ActiveSense,
    LV2_MIDI__Aftertouch, LV2_MIDI__Bender, LV2_MIDI__ChannelPressure, LV2_MIDI__Chunk,
    LV2_MIDI__Clock, LV2_MIDI__Continue, LV2_MIDI__Controller, LV2_MIDI__MidiEvent,
    LV2_MIDI__NoteOff, LV2_MIDI__NoteOn, LV2_MIDI__ProgramChange, LV2_MIDI__QuarterFrame,
    LV2_MIDI__Reset, LV2_MIDI__SongPosition, LV2_MIDI__SongSelect, LV2_MIDI__Start, LV2_MIDI__Stop,
    LV2_MIDI__SystemCommon, LV2_MIDI__SystemExclusive, LV2_MIDI__SystemMessage,
    LV2_MIDI__SystemRealtime, LV2_MIDI__Tick, LV2_MIDI__TuneRequest, LV2_MIDI__VoiceMessage,
    LV2_MIDI__benderValue, LV2_MIDI__binding, LV2_MIDI__byteNumber, LV2_MIDI__channel,
    LV2_MIDI__chunk, LV2_MIDI__controllerNumber, LV2_MIDI__controllerValue, LV2_MIDI__noteNumber,
    LV2_MIDI__pressure, LV2_MIDI__programNumber, LV2_MIDI__property, LV2_MIDI__songNumber,
    LV2_MIDI__songPosition, LV2_MIDI__status, LV2_MIDI__statusMask, LV2_MIDI__velocity,
    LV2_MORPH__AutoMorphPort, LV2_MORPH__MorphPort, LV2_MORPH__currentType, LV2_MORPH__interface,
    LV2_MORPH__supportsType, LV2_Midi_Controller_LV2_MIDI_CTL_ALL_NOTES_OFF,
    LV2_Midi_Controller_LV2_MIDI_CTL_ALL_SOUNDS_OFF,
    LV2_Midi_Controller_LV2_MIDI_CTL_DATA_DECREMENT,
    LV2_Midi_Controller_LV2_MIDI_CTL_DATA_INCREMENT,
    LV2_Midi_Controller_LV2_MIDI_CTL_E1_REVERB_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E2_TREMOLO_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E3_CHORUS_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E4_DETUNE_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_E5_PHASER_DEPTH,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE5,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE6,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE7,
    LV2_Midi_Controller_LV2_MIDI_CTL_GENERAL_PURPOSE8, LV2_Midi_Controller_LV2_MIDI_CTL_HOLD2,
    LV2_Midi_Controller_LV2_MIDI_CTL_LEGATO_FOOTSWITCH,
    LV2_Midi_Controller_LV2_MIDI_CTL_LOCAL_CONTROL_SWITCH,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_BALANCE, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_BANK,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_BREATH, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_DATA_ENTRY,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_EFFECT1, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_EFFECT2,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_EXPRESSION, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_FOOT,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE1,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE2,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE3,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_GENERAL_PURPOSE4,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_MAIN_VOLUME,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_MODWHEEL, LV2_Midi_Controller_LV2_MIDI_CTL_LSB_PAN,
    LV2_Midi_Controller_LV2_MIDI_CTL_LSB_PORTAMENTO_TIME, LV2_Midi_Controller_LV2_MIDI_CTL_MONO1,
    LV2_Midi_Controller_LV2_MIDI_CTL_MONO2, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_BALANCE,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_BANK, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_BREATH,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_DATA_ENTRY, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_EFFECT1,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_EFFECT2, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_EXPRESSION,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_FOOT,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE1,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE2,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE3,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_GENERAL_PURPOSE4,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_MAIN_VOLUME,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_MODWHEEL, LV2_Midi_Controller_LV2_MIDI_CTL_MSB_PAN,
    LV2_Midi_Controller_LV2_MIDI_CTL_MSB_PORTAMENTO_TIME,
    LV2_Midi_Controller_LV2_MIDI_CTL_NRPN_LSB, LV2_Midi_Controller_LV2_MIDI_CTL_NRPN_MSB,
    LV2_Midi_Controller_LV2_MIDI_CTL_OMNI_OFF, LV2_Midi_Controller_LV2_MIDI_CTL_OMNI_ON,
    LV2_Midi_Controller_LV2_MIDI_CTL_PORTAMENTO,
    LV2_Midi_Controller_LV2_MIDI_CTL_PORTAMENTO_CONTROL,
    LV2_Midi_Controller_LV2_MIDI_CTL_RESET_CONTROLLERS, LV2_Midi_Controller_LV2_MIDI_CTL_RPN_LSB,
    LV2_Midi_Controller_LV2_MIDI_CTL_RPN_MSB, LV2_Midi_Controller_LV2_MIDI_CTL_SC10,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC1_SOUND_VARIATION,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC2_TIMBRE, LV2_Midi_Controller_LV2_MIDI_CTL_SC3_RELEASE_TIME,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC4_ATTACK_TIME,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC5_BRIGHTNESS, LV2_Midi_Controller_LV2_MIDI_CTL_SC6,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC7, LV2_Midi_Controller_LV2_MIDI_CTL_SC8,
    LV2_Midi_Controller_LV2_MIDI_CTL_SC9, LV2_Midi_Controller_LV2_MIDI_CTL_SOFT_PEDAL,
    LV2_Midi_Controller_LV2_MIDI_CTL_SOSTENUTO, LV2_Midi_Controller_LV2_MIDI_CTL_SUSTAIN,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_ACTIVE_SENSE, LV2_Midi_Message_Type_LV2_MIDI_MSG_BENDER,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_CHANNEL_PRESSURE, LV2_Midi_Message_Type_LV2_MIDI_MSG_CLOCK,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_CONTINUE, LV2_Midi_Message_Type_LV2_MIDI_MSG_CONTROLLER,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_INVALID, LV2_Midi_Message_Type_LV2_MIDI_MSG_MTC_QUARTER,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_NOTE_OFF, LV2_Midi_Message_Type_LV2_MIDI_MSG_NOTE_ON,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_NOTE_PRESSURE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_PGM_CHANGE, LV2_Midi_Message_Type_LV2_MIDI_MSG_RESET,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_SONG_POS, LV2_Midi_Message_Type_LV2_MIDI_MSG_SONG_SELECT,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_START, LV2_Midi_Message_Type_LV2_MIDI_MSG_STOP,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_SYSTEM_EXCLUSIVE,
    LV2_Midi_Message_Type_LV2_MIDI_MSG_TUNE_REQUEST, LV2_OPTIONS__Option, LV2_OPTIONS__interface,
    LV2_OPTIONS__options, LV2_OPTIONS__requiredOption, LV2_OPTIONS__supportedOption,
    LV2_Options_Context_LV2_OPTIONS_BLANK, LV2_Options_Context_LV2_OPTIONS_INSTANCE,
    LV2_Options_Context_LV2_OPTIONS_PORT, LV2_Options_Context_LV2_OPTIONS_RESOURCE,
    LV2_Options_Status_LV2_OPTIONS_ERR_BAD_KEY, LV2_Options_Status_LV2_OPTIONS_ERR_BAD_SUBJECT,
    LV2_Options_Status_LV2_OPTIONS_ERR_BAD_VALUE, LV2_Options_Status_LV2_OPTIONS_ERR_UNKNOWN,
    LV2_Options_Status_LV2_OPTIONS_SUCCESS, LV2_PARAMETERS__CompressorControls,
    LV2_PARAMETERS__ControlGroup, LV2_PARAMETERS__EnvelopeControls, LV2_PARAMETERS__FilterControls,
    LV2_PARAMETERS__OscillatorControls, LV2_PARAMETERS__amplitude, LV2_PARAMETERS__attack,
    LV2_PARAMETERS__bypass, LV2_PARAMETERS__cutoffFrequency, LV2_PARAMETERS__decay,
    LV2_PARAMETERS__delay, LV2_PARAMETERS__dryLevel, LV2_PARAMETERS__frequency,
    LV2_PARAMETERS__gain, LV2_PARAMETERS__hold, LV2_PARAMETERS__pulseWidth, LV2_PARAMETERS__ratio,
    LV2_PARAMETERS__release, LV2_PARAMETERS__resonance, LV2_PARAMETERS__sampleRate,
    LV2_PARAMETERS__sustain, LV2_PARAMETERS__threshold, LV2_PARAMETERS__waveform,
    LV2_PARAMETERS__wetDryRatio, LV2_PARAMETERS__wetLevel, LV2_PATCH__Ack, LV2_PATCH__Copy,
    LV2_PATCH__Delete, LV2_PATCH__Error, LV2_PATCH__Get, LV2_PATCH__Message, LV2_PATCH__Move,
    LV2_PATCH__Patch, LV2_PATCH__Post, LV2_PATCH__Put, LV2_PATCH__Request, LV2_PATCH__Response,
    LV2_PATCH__Set, LV2_PATCH__accept, LV2_PATCH__add, LV2_PATCH__body, LV2_PATCH__context,
    LV2_PATCH__destination, LV2_PATCH__property, LV2_PATCH__readable, LV2_PATCH__remove,
    LV2_PATCH__request, LV2_PATCH__sequenceNumber, LV2_PATCH__subject, LV2_PATCH__value,
    LV2_PATCH__wildcard, LV2_PATCH__writable, LV2_PORT_GROUPS__DiscreteGroup,
    LV2_PORT_GROUPS__Element, LV2_PORT_GROUPS__FivePointOneGroup,
    LV2_PORT_GROUPS__FivePointZeroGroup, LV2_PORT_GROUPS__FourPointZeroGroup,
    LV2_PORT_GROUPS__Group, LV2_PORT_GROUPS__InputGroup, LV2_PORT_GROUPS__MidSideGroup,
    LV2_PORT_GROUPS__MonoGroup, LV2_PORT_GROUPS__OutputGroup, LV2_PORT_GROUPS__SevenPointOneGroup,
    LV2_PORT_GROUPS__SevenPointOneWideGroup, LV2_PORT_GROUPS__SixPointOneGroup,
    LV2_PORT_GROUPS__StereoGroup, LV2_PORT_GROUPS__ThreePointZeroGroup, LV2_PORT_GROUPS__center,
    LV2_PORT_GROUPS__centerLeft, LV2_PORT_GROUPS__centerRight, LV2_PORT_GROUPS__element,
    LV2_PORT_GROUPS__group, LV2_PORT_GROUPS__left, LV2_PORT_GROUPS__lowFrequencyEffects,
    LV2_PORT_GROUPS__mainInput, LV2_PORT_GROUPS__mainOutput, LV2_PORT_GROUPS__rearCenter,
    LV2_PORT_GROUPS__rearLeft, LV2_PORT_GROUPS__rearRight, LV2_PORT_GROUPS__right,
    LV2_PORT_GROUPS__side, LV2_PORT_GROUPS__sideChainOf, LV2_PORT_GROUPS__sideLeft,
    LV2_PORT_GROUPS__sideRight, LV2_PORT_GROUPS__source, LV2_PORT_GROUPS__subGroupOf,
    LV2_PORT_PROPS__causesArtifacts, LV2_PORT_PROPS__continuousCV, LV2_PORT_PROPS__discreteCV,
    LV2_PORT_PROPS__displayPriority, LV2_PORT_PROPS__expensive, LV2_PORT_PROPS__hasStrictBounds,
    LV2_PORT_PROPS__logarithmic, LV2_PORT_PROPS__notAutomatic, LV2_PORT_PROPS__notOnGUI,
    LV2_PORT_PROPS__rangeSteps, LV2_PORT_PROPS__supportsStrictBounds, LV2_PORT_PROPS__trigger,
    LV2_PRESETS__Bank, LV2_PRESETS__Preset, LV2_PRESETS__bank, LV2_PRESETS__preset,
    LV2_PRESETS__value, LV2_RESIZE_PORT__asLargeAs, LV2_RESIZE_PORT__minimumSize,
    LV2_RESIZE_PORT__resize, LV2_Resize_Port_Status_LV2_RESIZE_PORT_ERR_NO_SPACE,
    LV2_Resize_Port_Status_LV2_RESIZE_PORT_ERR_UNKNOWN,
    LV2_Resize_Port_Status_LV2_RESIZE_PORT_SUCCESS, LV2_STATE__State, LV2_STATE__StateChanged,
    LV2_STATE__freePath, LV2_STATE__interface, LV2_STATE__loadDefaultState, LV2_STATE__makePath,
    LV2_STATE__mapPath, LV2_STATE__state, LV2_STATE__threadSafeRestore,
    LV2_State_Flags_LV2_STATE_IS_NATIVE, LV2_State_Flags_LV2_STATE_IS_POD,
    LV2_State_Flags_LV2_STATE_IS_PORTABLE, LV2_State_Status_LV2_STATE_ERR_BAD_FLAGS,
    LV2_State_Status_LV2_STATE_ERR_BAD_TYPE, LV2_State_Status_LV2_STATE_ERR_NO_FEATURE,
    LV2_State_Status_LV2_STATE_ERR_NO_PROPERTY, LV2_State_Status_LV2_STATE_ERR_NO_SPACE,
    LV2_State_Status_LV2_STATE_ERR_UNKNOWN, LV2_State_Status_LV2_STATE_SUCCESS, LV2_TIME__Position,
    LV2_TIME__Rate, LV2_TIME__Time, LV2_TIME__bar, LV2_TIME__barBeat, LV2_TIME__beat,
    LV2_TIME__beatUnit, LV2_TIME__beatsPerBar, LV2_TIME__beatsPerMinute, LV2_TIME__frame,
    LV2_TIME__framesPerSecond, LV2_TIME__position, LV2_TIME__speed, LV2_UI__CocoaUI,
    LV2_UI__Gtk3UI, LV2_UI__GtkUI, LV2_UI__PortNotification, LV2_UI__PortProtocol, LV2_UI__Qt4UI,
    LV2_UI__Qt5UI, LV2_UI__WindowsUI, LV2_UI__binary, LV2_UI__fixedSize, LV2_UI__floatProtocol,
    LV2_UI__idleInterface, LV2_UI__noUserResize, LV2_UI__notifyType, LV2_UI__parent,
    LV2_UI__peakProtocol, LV2_UI__plugin, LV2_UI__portIndex, LV2_UI__portMap,
    LV2_UI__portNotification, LV2_UI__portSubscribe, LV2_UI__protocol, LV2_UI__resize,
    LV2_UI__showInterface, LV2_UI__touch, LV2_UI__ui, LV2_UI__updateRate, LV2_UI__windowTitle,
    LV2_UNITS__Conversion, LV2_UNITS__Unit, LV2_UNITS__bar, LV2_UNITS__beat, LV2_UNITS__bpm,
    LV2_UNITS__cent, LV2_UNITS__cm, LV2_UNITS__coef, LV2_UNITS__conversion, LV2_UNITS__db,
    LV2_UNITS__degree, LV2_UNITS__frame, LV2_UNITS__hz, LV2_UNITS__inch, LV2_UNITS__khz,
    LV2_UNITS__km, LV2_UNITS__m, LV2_UNITS__mhz, LV2_UNITS__midiNote, LV2_UNITS__mile,
    LV2_UNITS__min, LV2_UNITS__mm, LV2_UNITS__ms, LV2_UNITS__name, LV2_UNITS__oct, LV2_UNITS__pc,
    LV2_UNITS__prefixConversion, LV2_UNITS__render, LV2_UNITS__s, LV2_UNITS__semitone12TET,
    LV2_UNITS__symbol, LV2_UNITS__unit, LV2_URID__map, LV2_URID__unmap, LV2_WORKER__interface,
    LV2_WORKER__schedule, LV2_Worker_Status_LV2_WORKER_ERR_NO_SPACE,
    LV2_Worker_Status_LV2_WORKER_ERR_UNKNOWN, LV2_Worker_Status_LV2_WORKER_SUCCESS,
    LV2_ATOM_PREFIX, LV2_ATOM_REFERENCE_TYPE, LV2_ATOM_URI, LV2_ATOM__URI, LV2_ATOM__URID,
    LV2_BUF_SIZE_PREFIX, LV2_BUF_SIZE_URI, LV2_CORE_PREFIX, LV2_CORE_URI, LV2_DATA_ACCESS_PREFIX,
    LV2_DATA_ACCESS_URI, LV2_DYN_MANIFEST_PREFIX, LV2_DYN_MANIFEST_URI, LV2_INSTANCE_ACCESS_URI,
    LV2_LOG_PREFIX, LV2_LOG_URI, LV2_MIDI_PREFIX, LV2_MIDI_URI, LV2_MORPH_PREFIX, LV2_MORPH_URI,
    LV2_OPTIONS_PREFIX, LV2_OPTIONS_URI, LV2_PARAMETERS_PREFIX, LV2_PARAMETERS_URI,
    LV2_PATCH_PREFIX, LV2_PATCH_URI, LV2_PORT_GROUPS_PREFIX, LV2_PORT_GROUPS_URI,
    LV2_PORT_PROPS_PREFIX, LV2_PORT_PROPS_URI, LV2_PRESETS_PREFIX, LV2_PRESETS_URI,
    LV2_RESIZE_PORT_PREFIX, LV2_RESIZE_PORT_URI, LV2_STATE_PREFIX, LV2_STATE_URI, LV2_TIME_PREFIX,
    LV2_TIME_URI, LV2_UI_PREFIX, LV2_UI_URI, LV2_UI__UI, LV2_UI__X11UI, LV2_UNITS_PREFIX,
    LV2_UNITS_URI, LV2_URID_MAP_URI, LV2_URID_PREFIX, LV2_URID_UNMAP_URI, LV2_URID_URI,
    LV2_WORKER_PREFIX, LV2_WORKER_URI,
};

pub use bindings::{
    _LV2UI_Descriptor as LV2UI_Descriptor, _LV2UI_Idle_Interface as LV2UI_Idle_Interface,
    _LV2UI_Peak_Data as LV2UI_Peak_Data, _LV2UI_Port_Map as LV2UI_Port_Map,
    _LV2UI_Port_Subscribe as LV2UI_Port_Subscribe, _LV2UI_Resize as LV2UI_Resize,
    _LV2UI_Show_Interface as LV2UI_Show_Interface, _LV2UI_Touch as LV2UI_Touch,
    _LV2_Descriptor as LV2_Descriptor, _LV2_Feature as LV2_Feature, _LV2_Log as LV2_Log,
    _LV2_Options_Interface as LV2_Options_Interface, _LV2_Options_Option as LV2_Options_Option,
    _LV2_State_Interface as LV2_State_Interface, _LV2_URID_Map as LV2_URID_Map,
    _LV2_URID_Unmap as LV2_URID_Unmap, _LV2_Worker_Interface as LV2_Worker_Interface,
    _LV2_Worker_Schedule as LV2_Worker_Schedule,
};

pub use bindings::LV2_Atom_Event__bindgen_ty_1 as LV2_Atom_Event_Timestamp;
